### PR TITLE
Issue #1 Add support for backup/restore of file annotations.

### PR DESCRIPTION
**Pull request by jaypha**
Refer to https://tracker.moodle.org/browse/MDL-79151.

### CODE REVIEW

**Comment by paulholden** [comment]
Awesome, thanks @jaypha - will land this alongside the linked MDL :+1:

**Comment by jaypha** [comment]
MDL-79151 has landed, but there were last minute changes. So I will check to make sure this is up-to-date and resubmit it.

**Comment by paulholden** [comment]
Ah, great @jaypha, I'd meant to come back to this after your MDL landed

Just ping here when ready and I'll land it

**Comment by jaypha** [comment]
I just did a quick test, and the backup and restore are working. You can give it a test yourself and merge if you're happy.

**Pull request merged**
